# i3 configuration file snippet
# francesca (Alienware) running Ubuntu 24.04
# Copyright © Stephen Irons 2024-2026

# Set screen layout
# (Use arandr as a GUI for xrandr)
# exec --no-startup-id .screenlayout/2026-03-02-tatyana.sh
# exec --no-startup-id xrandr --output eDP-1 --primary --mode 2560x1600 --pos 0x0 --rotate normal --output DP-1 --off --output DP-2 --off --output DP-1-0 --off --output DP-1-1 --off --output DP-1-2 --off --output HDMI-1-0 --mode 2560x1440 --pos 2560x80 --rotate normal
exec --no-startup-id xrandr --output eDP-1 --mode 2560x1600 --pos 3840x224 --rotate normal --output DP-1 --off --output DP-2 --off --output DP-1-0 --off --output DP-1-1 --off --output DP-1-2 --off --output HDMI-1-0 --primary --mode 3840x2160 --pos 0x0 --rotate normal

set $display_L HDMI-1-0
set $display_R eDP-1


# Multiple monitors
workspace $ws1  output $display_R
workspace $ws2  output $display_L
workspace $ws3  output $display_R
workspace $ws4  output $display_L
workspace $ws5  output $display_R
workspace $ws6  output $display_L
workspace $ws7  output $display_R
workspace $ws8  output $display_L
workspace $ws9  output $display_R
workspace $ws10 output $display_L


# Swap mouse buttons
exec --no-startup-id xmodmap -e "pointer = 3 2 1"
# exec --no-startup-id xinput set-button-map "Primax Kensington Eagle Trackball" "3 2 1 4 5 6 7"
