#!/usr/bin/env python
#
# Copyright 2009 Canonical Ltd.
#
# Authors: Neil Jagdish Patel <neil.patel@canonical.com>
#          Jono Bacon <jono@ubuntu.com>
#          Stephen Irons
#
# This program is free software: you can redistribute it and/or modify it 
# under the terms of either or both of the following licenses:
#
# 1) the GNU Lesser General Public License version 3, as published by the 
# Free Software Foundation; and/or
# 2) the GNU Lesser General Public License version 2.1, as published by 
# the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but 
# WITHOUT ANY WARRANTY; without even the implied warranties of 
# MERCHANTABILITY, SATISFACTORY QUALITY or FITNESS FOR A PARTICULAR 
# PURPOSE.  See the applicable version of the GNU Lesser General Public 
# License for more details.
#
# You should have received a copy of both the GNU Lesser General Public 
# License version 3 and version 2.1 along with this program.  If not, see 
# <http://www.gnu.org/licenses/>
#

import gobject
import gtk
import appindicator
import os



menuitems = [
              ("Log out"     , "gnome-log-out", "gnome-session-quit --logout"   ),
              ("Switch user", "system-users"         , "dm-tool switch-to-greeter"     ),
              ("Power off"  , "system-shutdown-panel", "gnome-session-quit --power-off"),
            ]


if __name__ == "__main__":
  ind = appindicator.Indicator ("example-simple-client",
                              "indicator-messages",
                              appindicator.CATEGORY_APPLICATION_STATUS)
  ind.set_status (appindicator.STATUS_ACTIVE)
  ind.set_attention_icon ("indicator-messages-new")
  ind.set_icon("system-shutdown-panel")

  # create a menu
  menu = gtk.Menu()

  for m in menuitems:
     menu_item = gtk.ImageMenuItem(m[0])
     menu_item.set_image(gtk.image_new_from_icon_name(m[1], gtk.ICON_SIZE_MENU))
     menu_item.set_always_show_image(True)
     #menu.append(menu_item)
     #menu_item.connect("activate", menu_action, m[2])
     menu_item.connect("activate", lambda w, cmd: os.system(cmd), m[2])
     menu_item.show()
     menu.append(menu_item)

  ind.set_menu(menu)

  gtk.main()

